default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: blog
  username: deploy
  password: root
test:
  <<: *default
  database: blog
  username: root
  password: root

production:
  <<: *default
  database: blog
  username: root
  password: root

